import React from 'react';
import logo from '../../public/logo.png';

/**
 * LoginPage Component
 * Renders the login page, 2FA setup, and 2FA verify screens.
 * All authentication state and handlers live in App.jsx and are passed as props.
 */
export default function LoginPage({
  is2FAPhase,
  setIs2FAPhase,
  loginUsername,
  setLoginUsername,
  loginPassword,
  setLoginPassword,
  loginError,
  loginLoading,
  use2FA,
  setUse2FA,
  otpCode,
  setOtpCode,
  tempSecret,
  totpQrUrl,
  copiedKey,
  handleLoginSubmit,
  handleVerify2FASetup,
  handleVerify2FALogin,
  handleCopyMFAKey,
  handleReset2FA,
  handleLaunchDemoMode
}) {
  // 2FA Setup screen
  if (is2FAPhase === 'setup') {
    return (
      <div className="login-page">
        <div className="login-bg-decorations">
          <div className="login-blob login-blob-1"></div>
          <div className="login-blob login-blob-2"></div>
        </div>

        <div className="login-card totp-setup-card">
          <button onClick={() => setIs2FAPhase('none')} className="btn-back" type="button">
            ← Back to login
          </button>

          <div className="login-header" style={{ textAlign: 'center' }}>
            <div className="totp-icon-header">🛡️</div>
            <h2>Setup Authenticator</h2>
            <p>Scan this QR code with Google Authenticator to enable 2-Factor Authentication (2FA)</p>
          </div>

          {loginError && (
            <div className="totp-error-alert">
              <span>⚠️ {loginError}</span>
            </div>
          )}

          <div className="totp-setup-body">
            <div className="qr-container">
              {totpQrUrl && <img src={totpQrUrl} alt="Google Authenticator QR Code" className="qr-code-img" />}
            </div>

            <div className="secret-display-box">
              <label style={{ fontWeight: '600', fontSize: '11px', display: 'block', marginBottom: '4px' }}>Manual Setup Key</label>
              <div className="secret-key-wrapper">
                <span className="secret-key-text">{tempSecret}</span>
                <button onClick={handleCopyMFAKey} className="btn-copy" type="button">
                  {copiedKey ? '✓ Copied' : '📋 Copy'}
                </button>
              </div>
            </div>

            <form onSubmit={handleVerify2FASetup} className="login-form">
              <div className="form-group">
                <label htmlFor="otpCode">6-Digit Verification Code</label>
                <input
                  id="otpCode"
                  type="text"
                  pattern="\d*"
                  maxLength="6"
                  className="form-input text-center letter-spacing-lg"
                  placeholder="000000"
                  value={otpCode}
                  onChange={(e) => setOtpCode(e.target.value.replace(/\D/g, ''))}
                  required
                  autoFocus
                />
              </div>

              <button type="submit" className="btn-primary-login" disabled={loginLoading || otpCode.length !== 6}>
                {loginLoading ? 'Verifying...' : 'Verify & Enable 2FA'}
              </button>
            </form>
          </div>
        </div>
      </div>
    );
  }

  // 2FA Verify screen
  if (is2FAPhase === 'verify') {
    return (
      <div className="login-page">
        <div className="login-bg-decorations">
          <div className="login-blob login-blob-1"></div>
          <div className="login-blob login-blob-2"></div>
        </div>

        <div className="login-card totp-verify-card">
          <button onClick={() => setIs2FAPhase('none')} className="btn-back" type="button">
            ← Back to login
          </button>

          <div className="login-header" style={{ textAlign: 'center' }}>
            <div className="totp-icon-header">🛡️</div>
            <h2>MFA Verification</h2>
            <p>Enter the 6-digit code generated by your Google Authenticator app for <strong>{loginUsername}</strong></p>
          </div>

          {loginError && (
            <div className="totp-error-alert">
              <span>⚠️ {loginError}</span>
            </div>
          )}

          <form onSubmit={handleVerify2FALogin} className="login-form">
            <div className="form-group">
              <label htmlFor="otpCodeVerify">Authenticator Code</label>
              <input
                id="otpCodeVerify"
                type="text"
                pattern="\d*"
                maxLength="6"
                className="form-input text-center letter-spacing-lg"
                placeholder="000000"
                value={otpCode}
                onChange={(e) => setOtpCode(e.target.value.replace(/\D/g, ''))}
                required
                autoFocus
              />
            </div>

            <button type="submit" className="btn-primary-login" disabled={loginLoading || otpCode.length !== 6}>
              {loginLoading ? 'Authenticating...' : 'Verify & Sign In'}
            </button>
          </form>

          <div style={{ textAlign: 'center', marginTop: '12px' }}>
            <button onClick={handleReset2FA} className="btn-reset-2fa" style={{ fontSize: '11px', color: '#ef4444', textDecoration: 'underline', cursor: 'pointer' }}>
              Reset 2FA Setup
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Main login screen
  return (
    <div className="login-page">
      <div className="login-bg-decorations">
        <div className="login-blob login-blob-1"></div>
        <div className="login-blob login-blob-2"></div>
      </div>

      <div className="login-card">
        <div className="login-header">
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '8px' }}>
            <img src={logo} alt="Island Chill Logo" style={{ height: '48px', width: 'auto' }} />
          </div>
          <h2 style={{ textAlign: 'center' }}>Island Chill</h2>
          <p style={{ textAlign: 'center' }}>Sign in to manage bottling and warehouse production</p>
        </div>

        {loginError && (
          <div className="totp-error-alert">
            <span>⚠️ {loginError}</span>
          </div>
        )}

        <form onSubmit={handleLoginSubmit} className="login-form">
          <div className="form-group">
            <label>Username / Email</label>
            <div className="input-wrapper">
              <span className="input-icon">👤</span>
              <input
                type="text"
                className="form-input-icon"
                placeholder="administrator"
                value={loginUsername}
                onChange={(e) => setLoginUsername(e.target.value)}
                disabled={loginLoading}
                required
              />
            </div>
          </div>

          <div className="form-group">
            <label>Password</label>
            <div className="input-wrapper">
              <span className="input-icon">🔒</span>
              <input
                type="password"
                className="form-input-icon"
                value={loginPassword}
                onChange={(e) => setLoginPassword(e.target.value)}
                disabled={loginLoading}
                required
              />
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', margin: '4px 0' }}>
            <input
              type="checkbox"
              id="totp-toggle"
              checked={use2FA || localStorage.getItem(`totp_enabled_${loginUsername}`) === 'true'}
              disabled={localStorage.getItem(`totp_enabled_${loginUsername}`) === 'true'}
              onChange={(e) => setUse2FA(e.target.checked)}
              style={{ width: '16px', height: '16px', cursor: 'pointer' }}
            />
            <label htmlFor="totp-toggle" style={{ fontSize: '13px', fontWeight: '500', cursor: 'pointer' }}>
              Secure with Google Authenticator
              {localStorage.getItem(`totp_enabled_${loginUsername}`) === 'true' && (
                <span style={{ color: 'var(--success)', fontWeight: 'bold', marginLeft: '6px' }}>(Enabled)</span>
              )}
            </label>
          </div>

          <button type="submit" className="btn-primary-login" disabled={loginLoading} style={{ marginTop: '16px' }}>
            {loginLoading ? 'Authenticating...' : 'Sign In'}
          </button>
        </form>

        <div style={{ marginTop: '16px', textAlign: 'center' }}>
          <button
            type="button"
            onClick={handleLaunchDemoMode}
            disabled={loginLoading}
            style={{ fontSize: '12px', color: 'var(--text-muted)', textDecoration: 'underline', cursor: 'pointer', background: 'none', border: 'none' }}
          >
            🧪 Launch Demo Mode (offline simulation)
          </button>
        </div>
      </div>
    </div>
  );
}
